### ISSUE TITLE
Could you explain me how to use it, please ?

### ISSUE THREAD

**Issue by Niloss** [ScottyBauer/Android_Kernel_CVE_POCs#2]
Hello !
I am new in Android area, and I wanted to know if you can explain me, or suggest some links to understand, how to use these .c files, please ?

Do we have to compile it with gcc and run them on the Android device or emulator, or do we have to include them into an application built with NDK, or do we have to do another thing ?

Thank you in advance for your response !

**Comment by ScottyBauer** [comment]
You just need the aarch64 compiler and the android NDK.

**Comment by ScottyBauer** [comment]
once you get both of those things you need to do the following:

scotty@scotty:~/android/aarch64-linux-android-4.9/bin$ export CC=`pwd`/aarch64-linux-android-gcc

cd to android ndk
scotty@scotty:~/android/android-ndk-r11c$ export NDK=`pwd`
scotty@scotty:~/android/android-ndk-r11c$ export SYSROOT="$NDK/platforms/android-21/arch-arm64"

cd to folder with .c
$CC --sysroot=$SYSROOT -g -O0 -fPIE -pie  CVESOMETHING.c -o CVE_BUG

then move CVE_BUG to the phone chmod 777 it and run it
