### ISSUE TITLE
How to compile CVE20170705??

### ISSUE THREAD

**Issue by baosj0** [ScottyBauer/Android_Kernel_CVE_POCs#8]

**Comment by ScottyBauer** [comment]
Did you get this one working?

**Comment by baosj0** [comment]
No, I dont know how to combine libnl and NDK on Windows..
Can you tell me how you set up your build environment???
libnl.tar.gz  <<<<----- I dont know how to compile it using NDK to get .so
file.

I'm totally new to android vulns.

2017-07-21 12:36 GMT+08:00 Scott Bauer <notifications@github.com>:

**Comment by ScottyBauer** [comment]
I'll upload all the .so files I used tonight as well as the command.

**Comment by baosj0** [comment]
Thanks a lot!
Have u done? I didnt see any files yet.

2017-08-03 1:11 GMT+08:00 Scott Bauer <notifications@github.com>:

**Comment by ScottyBauer** [comment]
Thanks for the reminder.

Compile like this:
$CC --sysroot=$SYSROOT -g -O0 -fPIE -pie -I/usr/include/libnl3 CVE20170705.c libnl.so libc++.so libm.so libc.so libdl.so -o CVE20170705

where CC is:

export CC=`pwd`/aarch64-linux-android-gcc
and SYSROOT is:

cd ../../android-ndk-r11c/                                                                                                                                                                                                                                                                             
export NDK=`pwd`                                                                                                                                     
export SYSROOT="$NDK/platforms/android-21/arch-arm64"

I've uploaded the so's in a new directory in the CVE pocs
